meta_product_name: "Beryl"
meta_title: "Beryl | Fullstack Web Developer"
meta_description: "I'm available to take freelance missions and help you build your website. I'm also looking for a full-time job, and a stimulating work environment."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards